//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Form
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userSurname { get; set; }
        public string userBirthday { get; set; }
        public string userGender { get; set; }
        public string userTel { get; set; }
        public string userSchoolName { get; set; }
        public string userSchoolEndYear { get; set; }
        public string userGrade { get; set; }
        public string userMail { get; set; }
        public string userPassword { get; set; }
        public string userSubject { get; set; }
        public string userMessage { get; set; }
        public string yetkiliMessage { get; set; }
        public static bool mailEkle(string userName,
                                    string userSurname,
                                    string userBirthday,
                                    string userGender,
                                    string userTel,
                                    string userSchoolName,
                                    string userSchoolEndYear,
                                    string userGrade,
                                    string userMail,
                                    string userPassword,
                                    string userSubject,
                                    string userMessage)
        {
            using (ProjeEntities1 ent = new ProjeEntities1())
            {

                Form f = new Form();
                f.userName = userName;
                f.userSurname = userSurname;
                f.userBirthday = userBirthday;
                f.userGender = userGender;
                f.userTel = userTel;
                f.userSchoolName = userSchoolName;
                f.userSchoolEndYear = userSchoolEndYear;
                f.userGrade = userGrade;
                f.userMail = userMail;
                f.userPassword = userPassword;
                f.userSubject = userSubject;
                f.userMessage = userMessage;

                ent.Set<Models.Form>().Add(f);
                ent.SaveChanges();

                return true;
            }

        }
    }
}
